version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: springboot-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    # Bạn có thể thêm các biến môi trường ở đây nếu cần
    # environment:
    #   - SPRING_PROFILES_ACTIVE=prod
