spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.umbljhvwrngmltqauobo
spring.datasource.password=Cinema2026Luan

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# FIX SUPABASE POOLER ISSUE
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=false
server.port=${PORT:8080}

# ==================== VNPay ====================
vnp.tmnCode=${VNP_TMN_CODE:11AXZA1C}
vnp.hashSecret=${VNP_HASH_SECRET:SWJ0K8KU51RTI8R2QONZPK6Z8OAVEMEN}
vnp.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.returnUrl=${VNP_RETURN_URL:http://localhost:8080/api/payment/vnpay-return-web}

# ==================== Frontend URL ====================
frontend.url=${FRONTEND_URL:http://localhost:3000}

# ==================== Email SMTP ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=banhluanbeo@gmail.com
spring.mail.password=ggaxjmrnxtakhxpi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
